origin/creatingREADME
ivancabeUIB/web-studies-IDEL pull request #11
Opened 2024-09-23 10:11 UTC by alexsegur

README

2024-09-23 10:14 UTC, ivancabeUIB requested changes

2024-09-23 10:14 UTC, ivancabeUIB commented on README.md
> +_Este proyecto busca promover la transición digital mediante el desarrollo de una plataforma en línea para obtener datos, analizarlos estadísticamente de forma pseudo-automatizada y generar conclusio
Buenas, tiene buena pinta pero añadiria algo mas de descripción sobre qué es el projecto. Un par de lineas más, algo más de descripción.

2024-09-23 10:16 UTC, alexsegur commented on README.md
> +_Este proyecto busca promover la transición digital mediante el desarrollo de una plataforma en línea para obtener datos, analizarlos estadísticamente de forma pseudo-automatizada y generar conclusio
Perfect. Sí, a mi tambien me parecía demasiado resumida. Ahora lo añadiré.

2024-09-23 10:19 UTC, ivancabeUIB requested changes

2024-09-23 10:19 UTC, ivancabeUIB commented on IDEL_web_project/frontend/templates/index.html
> +<br><div id="main_content" class="container mt-5">
porque este "```<br>``` "?

2024-09-23 16:41 UTC, ivancabeUIB commented
tiene muy buena pinta, mañana lo subimos!

2024-09-24 07:08 UTC, ivancabeUIB approved these changes

2024-09-24 07:09 UTC, merged